apiVersion: 1

datasources:
  - name: SKVE-TimescaleDB
    type: postgres
    uid: skve-tsdb
    access: proxy
    url: timescaledb:5432
    user: ${DB_USER}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: ${DB_PASSWORD}
    isDefault: true
    editable: false
